### ISSUE TITLE
wrong wallet

### ISSUE THREAD

**Issue by equals215** [Atrides/eth-proxy#14]
says wrong wallet on debian with last vesion whatever I put as wallet

**Comment by gnufred** [comment]
Same problem on Ubuntu 12.04 with latest version

**Comment by gnufred** [comment]
@equals215 I had the same problem and I started monkey patching and got the proxy to work. Then realized it didn't load the config file.
`WARNING proxy # Wallet: XXXXXX`

Turn out fixing this is very simple.
`cd eth-proxy; python ./eth-proxy.py`

**Comment by gnufred** [comment]
@Atrides Please specify in the readme that we have to start the miner from within the `eth-proxy` folder.

**Comment by cmal** [comment]
same problem. Does this relate to the IP address changes?

**Comment by cmal** [comment]
Solved. Because I have a comment `# ...` on the end of the line `WALLET = "0x..."`.

**Comment by Chelloo** [comment]
Wat you min ?!

Thomas Foubert ***@***.***> schrieb am Do. 4. Aug. 2022 um
19:51:
